### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by pi0** [Baroshem/nuxt-adyen-module#19]
- Injected plugin is in esm format and should be renamed to  `adyen.mjs` (see https://v3.nuxtjs.org/concepts/esm)
- It would be nice to support runtime config allowing updating configuration without rebuild
- Use [pathe](https://github.com/unjs/pathe) instead of `require('path')`

Nitro support is probably broken and module not working with Bridge and Nuxt 3 because of added server middleware. But migration shouldn't be hard:
- Add bridge to enable Nitro (https://v3.nuxtjs.org/getting-started/migration#module-migration)
- Instead of using `createMiddleware` directly in module, add `{ handle: require.resolve('./runtime/middleware' }` so that nitro is able to properly bundle this
- Intead of express and body-parser, you can use a simple [h3 app middleware(https://github.com/unjs/h3) it should normally work finally with vanilla Nuxt 2 and connect as well

**Comment by Baroshem** [comment]
Hi @pi0 

I tried implementing serverMiddleware with this nuxt bridge but failed seeing this error.

```
 ERROR  Rollup error: TypeError [ERR_INVALID_ARG_TYPE]: Could not load virtual:#server-middleware (imported by node_modules/@nuxt/nitro/dist/runtime/server/index.mjs): The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

This is how I have implemented new serverMiddleware. File paths might be different because I am fixing the same issue for my nuxt-bigcommerce module

```ts
this.addServerMiddleware({ handle: resolve('./runtime/server/middleware.ts'), options })
```

Also there is a warning in the console

```
 WARN  [worker] Cannot find module '<SYSTEM_PATH>/nuxt-bigcommerce/example/.nuxt/nitro/index.mjs'

  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
  at Function.Module._load (internal/modules/cjs/loader.js:730:27)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
  at MessagePort.<anonymous> (internal/main/worker_thread.js:177:24)
  at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:398:41)
  at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
```

New nuxt config with nuxt bridge

```ts
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  modules: ['../src/module.ts'],

  bigcommerce: {
    storefrontToken: process.env.BIGCOMMERCE_STOREFRONT_TOKEN,
    apiToken: process.env.BIGCOMMERCE_API_TOKEN,
    storeUrl: process.env.BIGCOMMERCE_STORE_URL,
    storeHash: process.env.BIGCOMMERCE_STORE_HASH,
    channelId: 1,
    enableServerMiddleware: true // Optional
    // includeValuesInRuntimeConfig: ['storefrontToken'] // Optional
  }
})
```

I would appreciate your feedback as I am quite new to the topic of Nuxt 3 :)

**Comment by pi0** [comment]
Can you please push your changes to a branch that I can locally check?

**Comment by Baroshem** [comment]
@pi0 

Sure, here you go -> https://github.com/Baroshem/nuxt-bigcommerce/pull/11

**Comment by Baroshem** [comment]
I noticed that Nuxt 3 does not support accessing app (via context.app['module']. This also would need to be removed in order to have full nuxt 3 support
