### ISSUE TITLE
[Bug]: getPaymentsDetails throws TypeError: Cannot set property 'paymentRef' of undefined

### ISSUE THREAD

**Issue by bokjo** [Baroshem/nuxt-adyen-module#22]
### Expected Behavior

getPaymentsDetails() should not throw TypeError and return data...

### Actual Behavior

After submitting a payment the returnUrl is never redirected and the page hangs,  back because getPaymentsDetails() function fails...

```sh
 ERROR  Error: Cannot set property 'paymentRef' of undefined, error code: undefined                                                                                                                                                   00:29:38


 ERROR  TypeError: Cannot set property 'paymentRef' of undefined                                                                                                                                                                      00:29:38

  at AdyenServerApi.getPaymentsDetails (node_modules/nuxt-adyen-module/dist/module.js:144:13)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async node_modules/nuxt-adyen-module/dist/module.js:272:22
```

https://github.com/Baroshem/nuxt-adyen-module/blob/a9f6eb6dc4c82d709f2c8471f23b01a6b07ad048/src/runtime/server.ts#L76

`this.paymentStore[orderRef].paymentRef = response.pspReference`

`this.paymentStore[orderRef]` is `undefined` to begin with and cannot be assigned in this way

p.s this is the case on a few other places through the code
pp.s some minimal unit tests are needed :)

### Possible Solution

https://github.com/Baroshem/nuxt-adyen-module/blob/a9f6eb6dc4c82d709f2c8471f23b01a6b07ad048/src/runtime/server.ts#L75

```js
if (!response.action) {
        this.paymentStore[orderRef]= { 
            paymentRef: response.pspReference,
            status: response.resultCode
         }
}
```

### Steps to reproduce

/

### What version of nuxt-adyen-module are you using?

2.0.0

### What version of Node.js are you using?

14

### What browser (and version) are you using?

Chrome - Version 96.0.4664.55 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hi @bokjo,

Thanks for raising this issue. I have added it to the 2.0.1 roadmap to fix in the upcoming new version release

**Comment by bokjo** [comment]
@here 

Added as part of https://github.com/Baroshem/nuxt-adyen-module/pull/26
